<a href="https://colab.research.google.com/github/finesketch/data_science/blob/main/Python_Data_Science_Handbook/03_Data_Manipulation_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas is a newer package built on top of NumPy, and provides an efficient implementation of a DataFrame. DataFrames are essentially multidimensional arrays with attached row and column labels, and often with heterogeneous types and/or missing data.

As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs.

Pandas, and in particular its Series and DataFrame objects, builds on the NumPy array structure and provides efficient access to these sorts of “data munging” tasks that occupy much of a data scientist’s time.

## Installing and Using Pandas

Installation of the Pandas library is very straigthforward, visit Pandas documentation for details, https://pandas.pydata.org.

Once installed, to start using Pandas is very easy as well.

In [1]:
import pandas
pandas.__version__

'1.1.5'

Alternatively, you can reference it as **pd**, extremely common in data science community.

In [2]:
import pandas as pd
pd.__version__

'1.1.5'

To get help on Pandas, try this:

In [3]:
pd?

## Introducing Pandas Objects

To think about Pandas data structure, it should consist of *row* and *column*, like database table.

In [4]:
import numpy as np
import pandas as pd

### The Pandas Series Object

A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

Series wraps both a sequence of *values* and a sequence of *indices*, which we can access with the values and index attributes.

In [11]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

The index is an array-like object of type pd.Index.

In [12]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
# data can be accessed by the associated index
data[1]

0.5

In [14]:
# or use range ":"
data[1:3]

1    0.50
2    0.75
dtype: float64

In [16]:
data[0:-1]

0    0.25
1    0.50
2    0.75
dtype: float64

### Series as Generalized Numpy Array

Series may look a 1-D Numpy array, but the main is the presence of the index.

Index in Pandas Series is explicit.

In [17]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [19]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [20]:
data[5]

0.5

### Series as Specialized Dictionary

It is like Python dictionary data structure, but more efficient like Numpy which using type-specific.

In [21]:
# use it like Python dictionary
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [22]:
# access data like a dictionary
population['California']

38332521

In [24]:
# unlike Python dictionary, Series also supports array_style operation
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

### Constructing Series Objects

A Series can be created using following function:

*pd.Series(data, index=index)*

In [25]:
# data can be a list or NumPy array, in which case index defaults to an integer sequence
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [28]:
# data can be a scalar, which is repeated to fill the specified index
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [29]:
# data can be a dictionary, in which index defaults to the sorted dictionary keys
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [30]:
# index can be "re-used", but the later will overwrite the previous one.
pd.Series({2:'a', 1:'b', 2:'c'})

2    c
1    b
dtype: object

In [31]:
# the index can be explicitly set if a different result is preferred
# "1:'b'" is removed from the results
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [32]:
python_list = [3, 7, 1, 3, 5]
numpy_list = np.array(python_list)
pd.Series(numpy_list)

0    3
1    7
2    1
3    3
4    5
dtype: int64

## The Pandas DataFrame Object

Besides Series, DataFrame is very important.

### Dataframe as a Generalized Numpy Array

Series is used for 1-D array with an index, and DataFrame is a 2-D array with row and column indices.

So DataFrame consists of one to many Series.

In [33]:
# first construct a new Series listing the area of each of the five states discussed in the previous section
area_dict = {'California': 423967, 
             'Texas': 695662, 
             'New York': 141297,
             'Florida': 170312, 
             'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [35]:
# now combine both population and area series together
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [36]:
# get index information
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [37]:
# get column information
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame as Specialized Dictionary

In [38]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [39]:
states['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

### Constructing DataFrame Objects

A DataFrame can be constructed in a variety of ways

In [40]:
# from a single Series object
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [42]:
# from a list of dicts
data = [{'a': i, 'b': 2 * i} for i in range(3)]
data


[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [43]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [44]:
# with missing keys will be filled with "NaN"
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [45]:
# from a dictionary of Series objects
pd.DataFrame({'population': population, 'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [55]:
# from a two-dimensional NumPy array
A = np.random.rand(3, 2)
A

array([[0.87638915, 0.89460666],
       [0.08504421, 0.03905478],
       [0.16983042, 0.8781425 ]])

In [56]:
pd.DataFrame(A, columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.876389  0.894607
b  0.085044  0.039055
c  0.169830  0.878143

In [53]:
# from a Numpy structured array
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [54]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

The Index object can be thought of either as an immutable array or as an ordered set.

In [57]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

### Index as Immutable Array

Use standard Python indexing notation to retrieve values or slices.

In [58]:
ind[1]

3

In [59]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [60]:
# Index objects also have many of the attributes familiar from NumPy arrays
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [61]:
# one difference: Index object is immutable, cannot be modified
ind[1] = 0

TypeError: ignored

### Index as Ordered Set

Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic. The Index object follows many of the conventions used by Python’s built-in set data structure, so that unions, intersections, differences, and other combinations can be computed in a familiar way.

In [62]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [63]:
# intersection
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [64]:
# union
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [65]:
# symmetric difference
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [66]:
# these operations may also be accessed via object methods
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [67]:
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [68]:
indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

## Data Indexing and Selection

### Data Selection in Series

#### Series as Dictionary

In [69]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [72]:
# Series object provides a mapping from a collection of keys to a collection of values
data['b']

0.5

In [71]:
# examine the keys/indices and values
'a' in data

True

In [74]:
# get all the keys
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [76]:
new_list = list(data.items())

In [77]:
type(new_list)

list

In [78]:
# Series objects can be modified or extended
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series as 1-D Array

In [79]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [80]:
# slciing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [81]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [82]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [83]:
data[['a', 'c', 'e']]

a    0.25
c    0.75
e    1.25
dtype: float64

### Indexes: LOC, ILOC, and IX

One guiding principle of Python code is that **explicit is better than implicit.**

In [84]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [85]:
# explicit index when indexing
data[1]

'a'

In [86]:
data[5]

'c'

In [87]:
# error here, not found
data[4]

KeyError: ignored

In [88]:
data[1:3]

3    b
5    c
dtype: object

In [89]:
# "loc" attribute allows indexing and slicing that always references the explicit index
data.loc[1] # like data[1]

'a'

In [90]:
data.loc[3] # like data[3]

'b'

In [91]:
data.loc[4] # like data[4]

KeyError: ignored

In [92]:
# "iloc" attribute allows indexing and slicing that always references the implicit Python-style index
data.iloc[1]. # implicit Python-style index (position based)

'b'

In [93]:
data.iloc[1:3] # implicit Python-style index (position based)

3    b
5    c
dtype: object

## Data Selection in DataFrame

Recall that a DataFrame acts in many ways like a two-dimensional or structured array, and in other ways like a dictionary of Series structures sharing the same index.

### DataFrame as a Dictionary

In [94]:
 area = pd.Series({'California': 423967, 
                   'Texas': 695662,
                   'New York': 141297, 
                   'Florida': 170312,
                   'Illinois': 149995})
pop = pd.Series({'California': 38332521, 
                 'Texas': 26448193,
                 'New York': 19651127, 
                 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [95]:
# dictionary-style to access the datya
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [96]:
# or access it using "attribute" property
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [97]:
# how about check this?
data.area is data['area']

True

In [98]:
# keep in mind that it does not work for all cases
# because DataFrame has a pop() method
data.pop is data['pop']

False

In [99]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [100]:
data.density is data['density']

True

### DataFrame as Two-Dimensional Array

We can examine the raw underlying data array using the values attribute

In [101]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [102]:
# transpose the DataFrame to swap rows and columns
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [103]:
# access a column
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [104]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [105]:
data.iloc[:3, :2]. # Pyhton-stype index

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [108]:
data.loc[:'Florida', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860

In [109]:
data.loc[:'California', :'area']

area
California  423967

In [111]:
data.loc[:'Florida', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860

In [112]:
data.ix[:3, :'pop']. # .ix is deprecated

AttributeError: ignored

In [113]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [115]:
# modify data
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

## Additional Indexing Conventions

In [116]:
# while indexing refers to columns, slicing refers to rows
data['Florida': 'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [117]:
# slices can also refer to rows by number rather than by index
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [118]:
# masking operations are also interpreted row-wise rather than column-wise
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

## Operating on Data in Pandas